//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEdit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GEdit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Error!.
        /// </summary>
        internal static string Editer_toolStripButton3_Click_Save_Error_ {
            get {
                return ResourceManager.GetString("Editer_toolStripButton3_Click_Save_Error_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Form1_tabControl1_MouseDown_Confirm {
            get {
                return ResourceManager.GetString("Form1_tabControl1_MouseDown_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to Close this Tab?.
        /// </summary>
        internal static string Form1_tabControl1_MouseDown_Would_you_like_to_Close_this_Tab_ {
            get {
                return ResourceManager.GetString("Form1_tabControl1_MouseDown_Would_you_like_to_Close_this_Tab_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a file!.
        /// </summary>
        internal static string Form1_toolStripButton2_Click_Pick_a_file_ {
            get {
                return ResourceManager.GetString("Form1_toolStripButton2_Click_Pick_a_file_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading file!.
        /// </summary>
        internal static string Settings_button3_Click_Error_loading_file_ {
            get {
                return ResourceManager.GetString("Settings_button3_Click_Error_loading_file_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Tab.
        /// </summary>
        internal static string Texttab_Texttab_New_Tab {
            get {
                return ResourceManager.GetString("Texttab_Texttab_New_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string Theme_button7_Click_Error_ {
            get {
                return ResourceManager.GetString("Theme_button7_Click_Error_", resourceCulture);
            }
        }
    }
}
